#!/bin/bash

API_DATA="../api_data.json"
SRC="rudder.py.src"
DST="rudder.py"
GENERATOR="./generate.py"
DELIMITER="#### Autogenerated code, DO NOT MODIFY"

cp ${API_DATA} .
cat <(sed -ne "0,/${DELIMITER}/p" ${SRC}) <(${GENERATOR}) <(sed -e "0,/${DELIMITER}/d" ${SRC}) > ${DST}
