#!/bin/bash
set -e

API_DATA="../api_data.json"
SRC="rudder.py.src"
DST="rudder.py"
GENERATOR="generate.py"
DELIMITER="#### Autogenerated code, DO NOT MODIFY"
TEMP="./temp"
PYTHON_BINARY="/usr/bin/python"
if command -v python3 &>/dev/null; then
    PYTHON_BINARY="/usr/bin/python3"
fi
${PYTHON_BINARY} ${GENERATOR} > ${TEMP}
sed "/${DELIMITER}/r${TEMP}" ${SRC} > ${DST}

rm "${TEMP}"
