#!/bin/bash
set -e

API_DATA="../api_data.json"
SRC="rudder.py.src"
DST="rudder.py"
GENERATOR="./generate.py"
DELIMITER="#### Autogenerated code, DO NOT MODIFY"
TEMP="./temp"

${GENERATOR} > ${TEMP}
sed "/${DELIMITER}/r${TEMP}" ${SRC} > ${DST}

rm "${TEMP}"
